 source('~/Documents/GitHub/specimR/R/roi.R')
 source('~/Documents/GitHub/specimR/R/shinyLength.R')
 source('~/Documents/GitHub/specimR/R/normalize.R')
 source('~/Documents/GitHub/specimR/R/coreImage.R')
 source('~/Documents/GitHub/specimR/R/full_spectra.R')
 source('~/Documents/GitHub/specimR/R/SpectralCalculationsNick.R')
 library(shiny)
 library(raster)
 library(specimR)
 library(magrittr)
 library(dplyr)
 library(readr)
 library(tidyr)
 library(tibble)
 library(tictoc)
 f <- full_spectra()
f <- full_spectra(chunk.top = 0,chunk.bot = 3.5,chunk.step = .25)
