 source('~/Documents/GitHub/specimR/R/roi.R')
 source('~/Documents/GitHub/specimR/R/shinyLength.R')
 source('~/Documents/GitHub/specimR/R/normalize.R')
 source('~/Documents/GitHub/specimR/R/coreImage.R')
 source('~/Documents/GitHub/specimR/R/SpectralCalculationsNick.R')
 library(shiny)
 library(raster)
 library(specimR)
 library(magrittr)
 library(dplyr)
 library(readr)
 library(tidyr)
 library(tibble)
 library(tictoc)
 f <- full_spectra()
2:36
